export const diseases = [
    // --- CARDIOVASCULAR (cv) ---
    { id: "cv-htn", system: "cardiovascular", name: "High Blood Pressure" },
    { id: "cv-arr", system: "cardiovascular", name: "Irregular Heartbeat" },
    { id: "cv-cad", system: "cardiovascular", name: "Heart Disease" },
    { id: "cv-hfail", system: "cardiovascular", name: "Heart Failure" },
    { id: "cv-pad", system: "cardiovascular", name: "Poor Circulation" },
    { id: "cv-vlv", system: "cardiovascular", name: "Heart Valve Issue" },
    { id: "cv-anm", system: "cardiovascular", name: "Anemia" },
    { id: "cv-dvt", system: "cardiovascular", name: "Blood Clot" },
    { id: "cv-hypo", system: "cardiovascular", name: "Low Blood Pressure" },
    { id: "cv-chol", system: "cardiovascular", name: "High Cholesterol" },

    // --- RESPIRATORY (resp) ---
    { id: "resp-ast", system: "respiratory", name: "Asthma" },
    { id: "resp-copd", system: "respiratory", name: "Chronic Lung Disease" },
    { id: "resp-brn", system: "respiratory", name: "Bronchitis" },
    { id: "resp-pnu", system: "respiratory", name: "Pneumonia" },
    { id: "resp-slp", system: "respiratory", name: "Sleep Apnea" },
    { id: "resp-sin", system: "respiratory", name: "Sinus Infection" },
    { id: "resp-all", system: "respiratory", name: "Hay Fever / Allergies" },
    { id: "resp-emp", system: "respiratory", name: "Emphysema" },
    { id: "resp-pfe", system: "respiratory", name: "Fluid in Lungs" },
    { id: "resp-tbc", system: "respiratory", name: "Tuberculosis" },

    // --- DIGESTIVE (dig) ---
    { id: "dig-gerd", system: "digestive", name: "Acid Reflux / GERD" },
    { id: "dig-ibs", system: "digestive", name: "Irritable Bowel (IBS)" },
    { id: "dig-gast", system: "digestive", name: "Stomach Inflammation" },
    { id: "dig-pud", system: "digestive", name: "Stomach Ulcer" },
    { id: "dig-cel", system: "digestive", name: "Celiac Disease" },
    { id: "dig-crh", system: "digestive", name: "Crohn's Disease" },
    { id: "dig-uc", system: "digestive", name: "Ulcerative Colitis" },
    { id: "dig-div", system: "digestive", name: "Diverticulitis" },
    { id: "dig-gall", system: "digestive", name: "Gallstones" },
    { id: "dig-con", system: "digestive", name: "Chronic Constipation" },

    // --- NEUROLOGICAL (neuro) ---
    { id: "neuro-mig", system: "nervous", name: "Migraine" },
    { id: "neuro-epi", system: "nervous", name: "Seizures / Epilepsy" },
    { id: "neuro-ms", system: "nervous", name: "Multiple Sclerosis" },
    { id: "neuro-par", system: "nervous", name: "Parkinson's" },
    { id: "neuro-alz", system: "nervous", name: "Dementia" },
    { id: "neuro-neu", system: "nervous", name: "Nerve Pain" },
    { id: "neuro-str", system: "nervous", name: "Stroke History" },
    { id: "neuro-ins", system: "nervous", name: "Insomnia" },
    { id: "neuro-vert", system: "nervous", name: "Vertigo / Dizziness" },
    { id: "neuro-cts", system: "nervous", name: "Carpal Tunnel" },

    // --- MUSCULOSKELETAL (ms) ---
    { id: "ms-oa", system: "musculoskeletal", name: "Osteoarthritis" },
    { id: "ms-ra", system: "musculoskeletal", name: "Rheumatoid Arthritis" },
    {
        id: "ms-ost",
        system: "musculoskeletal",
        name: "Osteoporosis",
    },
    { id: "ms-fbr", system: "musculoskeletal", name: "Fibromyalgia" },
    { id: "ms-gout", system: "musculoskeletal", name: "Gout" },
    { id: "ms-scol", system: "musculoskeletal", name: "Scoliosis" },
    { id: "ms-ten", system: "musculoskeletal", name: "Tendinitis" },
    { id: "ms-bur", system: "musculoskeletal", name: "Bursitis" },
    { id: "ms-disc", system: "musculoskeletal", name: "Slipped Disc" },
    { id: "ms-stn", system: "musculoskeletal", name: "Spinal Stenosis" },

    // --- ENDOCRINE (endo) ---
    { id: "endo-d1", system: "endocrine", name: "Type 1 Diabetes" },
    { id: "endo-d2", system: "endocrine", name: "Type 2 Diabetes" },
    { id: "endo-hypo", system: "endocrine", name: "Underactive Thyroid" },
    { id: "endo-hyper", system: "endocrine", name: "Overactive Thyroid" },
    { id: "endo-pcos", system: "endocrine", name: "PCOS" },
    { id: "endo-adr", system: "endocrine", name: "Adrenal Issue" },
    { id: "endo-hash", system: "endocrine", name: "Hashimoto's" },
    { id: "endo-met", system: "endocrine", name: "Metabolic Syndrome" },
    { id: "endo-pit", system: "endocrine", name: "Pituitary Issue" },
    { id: "endo-par", system: "endocrine", name: "Hyperparathyroid" },

    // --- IMMUNE (imm) ---
    { id: "imm-lup", system: "immune", name: "Lupus" },
    { id: "imm-psa", system: "immune", name: "Psoriatic Arthritis" },
    { id: "imm-hiv", system: "immune", name: "HIV / AIDS" },
    { id: "imm-cfs", system: "immune", name: "Chronic Fatigue" },
    { id: "imm-lym", system: "immune", name: "Lyme Disease" },
    { id: "imm-gra", system: "immune", name: "Graves' Disease" },
    { id: "imm-anc", system: "immune", name: "Severe Allergy History" },
    { id: "imm-sj", system: "immune", name: "Dry Eye/Mouth (Sjogren's)" },
    { id: "imm-vas", system: "immune", name: "Vasculitis" },
    { id: "imm-immu", system: "immune", name: "Low Immunity" },

    // --- DERMATOLOGICAL (derm) ---
    { id: "derm-ecz", system: "dermatological", name: "Eczema" },
    { id: "derm-pso", system: "dermatological", name: "Psoriasis" },
    { id: "derm-ros", system: "dermatological", name: "Rosacea" },
    { id: "derm-mel", system: "dermatological", name: "Skin Cancer History" },
    { id: "derm-acn", system: "dermatological", name: "Severe Acne" },
    { id: "derm-urt", system: "dermatological", name: "Hives" },
    { id: "derm-vit", system: "dermatological", name: "Vitiligo" },
    { id: "derm-cel", system: "dermatological", name: "Skin Infection" },
    { id: "derm-alo", system: "dermatological", name: "Hair Loss (Alopecia)" },
    { id: "derm-her", system: "dermatological", name: "Shingles" },

    // --- URINARY (uro) ---
    { id: "uro-ckd", system: "urinary", name: "Kidney Disease" },
    { id: "uro-uti", system: "urinary", name: "UTI (Urinary Infection)" },
    { id: "uro-stn", system: "urinary", name: "Kidney Stones" },
    { id: "uro-inc", system: "urinary", name: "Bladder Control Issue" },
    { id: "uro-bph", system: "urinary", name: "Enlarged Prostate" },
    { id: "uro-cys", system: "urinary", name: "Bladder Pain" },
    { id: "uro-pne", system: "urinary", name: "Kidney Infection" },
    { id: "uro-glom", system: "urinary", name: "Kidney Inflammation" },
    { id: "uro-ovr", system: "urinary", name: "Overactive Bladder" },
    { id: "uro-pro", system: "urinary", name: "Prostate Inflammation" },

    // --- REPRODUCTIVE (repr) ---
    { id: "repr-pms", system: "reproductive", name: "Severe PMS / PMDD" },
    { id: "repr-endo", system: "reproductive", name: "Endometriosis" },
    { id: "repr-inf", system: "reproductive", name: "Infertility Issues" },
    { id: "repr-meno", system: "reproductive", name: "Menopause Symptoms" },
    { id: "repr-fib", system: "reproductive", name: "Uterine Fibroids" },
    { id: "repr-erect", system: "reproductive", name: "Erectile Dysfunction" },
    { id: "repr-std", system: "reproductive", name: "History of STI/STD" },
    { id: "repr-cyst", system: "reproductive", name: "Ovarian Cysts" },
    { id: "repr-pros", system: "reproductive", name: "Prostate Health Issue" },
    {
        id: "repr-preg",
        system: "reproductive",
        name: "Pregnancy-Related Issue",
    },

    // --- MENTAL HEALTH (ment) ---
    { id: "ment-gad", system: "mental", name: "Anxiety" },
    { id: "ment-mdd", system: "mental", name: "Depression" },
    { id: "ment-bip", system: "mental", name: "Bipolar Disorder" },
    { id: "ment-ptsd", system: "mental", name: "PTSD" },
    { id: "ment-ocd", system: "mental", name: "OCD" },
    { id: "ment-adhd", system: "mental", name: "ADHD" },
    { id: "ment-panic", system: "mental", name: "Panic Attacks" },
    { id: "ment-post", system: "mental", name: "Postpartum Depression" },
    { id: "ment-sch", system: "mental", name: "Schizophrenia" },
    { id: "ment-sad", system: "mental", name: "Seasonal Depression" },
];
