export const diseases = [
    // --- GENERAL & LIFESTYLE (gen) ---
    {
        id: "gen-htn",
        system: "general",
        name: "Hypertension (High Blood Pressure)",
    },
    { id: "gen-chol", system: "general", name: "High Cholesterol" },
    { id: "gen-d1", system: "general", name: "Type 1 Diabetes" },
    { id: "gen-d2", system: "general", name: "Type 2 Diabetes" },
    { id: "gen-met", system: "general", name: "Metabolic Syndrome" },
    { id: "gen-fat", system: "general", name: "Chronic Fatigue" },
    { id: "gen-obs", system: "general", name: "Weight Management / Obesity" },
    { id: "gen-slp", system: "general", name: "Insomnia / Sleep Issues" },
    { id: "gen-str", system: "general", name: "Chronic Stress" },
    { id: "gen-inf", system: "general", name: "Chronic Inflammation" },

    // --- CARDIOVASCULAR (cv) ---
    {
        id: "cv-arr",
        system: "cardiovascular",
        name: "Irregular Heartbeat (Arrhythmia)",
    },
    { id: "cv-cad", system: "cardiovascular", name: "Heart Disease (CAD)" },
    { id: "cv-hfail", system: "cardiovascular", name: "Heart Failure" },
    { id: "cv-pad", system: "cardiovascular", name: "Poor Circulation (PAD)" },
    { id: "cv-vlv", system: "cardiovascular", name: "Heart Valve Issue" },
    { id: "cv-anm", system: "cardiovascular", name: "Anemia" },
    { id: "cv-dvt", system: "cardiovascular", name: "Blood Clot / DVT" },
    { id: "cv-stroke", system: "cardiovascular", name: "Stroke History / TIA" },
    { id: "cv-aneur", system: "cardiovascular", name: "Aneurysm History" },
    { id: "cv-mur", system: "cardiovascular", name: "Heart Murmur" },

    // --- RESPIRATORY (resp) ---
    { id: "resp-ast", system: "respiratory", name: "Asthma" },
    {
        id: "resp-copd",
        system: "respiratory",
        name: "COPD / Chronic Lung Disease",
    },
    { id: "resp-brn", system: "respiratory", name: "Chronic Bronchitis" },
    { id: "resp-slp", system: "respiratory", name: "Sleep Apnea" },
    { id: "resp-sin", system: "respiratory", name: "Chronic Sinusitis" },
    {
        id: "resp-all",
        system: "respiratory",
        name: "Hay Fever / Seasonal Allergies",
    },
    { id: "resp-emp", system: "respiratory", name: "Emphysema" },
    { id: "resp-fib", system: "respiratory", name: "Pulmonary Fibrosis" },
    { id: "resp-canc", system: "respiratory", name: "Lung Cancer" },
    { id: "resp-pht", system: "respiratory", name: "Pulmonary Hypertension" },

    // --- DIGESTIVE (dig) ---
    { id: "dig-gerd", system: "digestive", name: "Acid Reflux / GERD" },
    { id: "dig-ibs", system: "digestive", name: "Irritable Bowel (IBS)" },
    { id: "dig-gast", system: "digestive", name: "Gastritis" },
    { id: "dig-pud", system: "digestive", name: "Stomach Ulcer" },
    { id: "dig-cel", system: "digestive", name: "Celiac Disease" },
    { id: "dig-crh", system: "digestive", name: "Crohn's Disease" },
    { id: "dig-uc", system: "digestive", name: "Ulcerative Colitis" },
    { id: "dig-div", system: "digestive", name: "Diverticulitis" },
    { id: "dig-gall", system: "digestive", name: "Gallstones" },
    { id: "dig-con", system: "digestive", name: "Chronic Constipation" },

    // --- NEUROLOGICAL (neuro) ---
    { id: "neuro-mig", system: "nervous", name: "Migraine" },
    { id: "neuro-epi", system: "nervous", name: "Seizures / Epilepsy" },
    { id: "neuro-ms", system: "nervous", name: "Multiple Sclerosis" },
    { id: "neuro-par", system: "nervous", name: "Parkinson's" },
    { id: "neuro-alz", system: "nervous", name: "Dementia / Alzheimer's" },
    { id: "neuro-neu", system: "nervous", name: "Neuropathy / Nerve Pain" },
    { id: "neuro-cts", system: "nervous", name: "Carpal Tunnel" },
    { id: "neuro-trig", system: "nervous", name: "Trigeminal Neuralgia" },
    { id: "neuro-als", system: "nervous", name: "ALS / Motor Neuron Disease" },
    { id: "neuro-vert", system: "nervous", name: "Chronic Dizziness" },

    // --- MUSCULOSKELETAL (ms) ---
    { id: "ms-oa", system: "musculoskeletal", name: "Osteoarthritis" },
    { id: "ms-ra", system: "musculoskeletal", name: "Rheumatoid Arthritis" },
    { id: "ms-psa", system: "musculoskeletal", name: "Psoriatic Arthritis" },
    { id: "ms-ost", system: "musculoskeletal", name: "Osteoporosis" },
    { id: "ms-fbr", system: "musculoskeletal", name: "Fibromyalgia" },
    { id: "ms-gout", system: "musculoskeletal", name: "Gout" },
    { id: "ms-scol", system: "musculoskeletal", name: "Scoliosis" },
    { id: "ms-ten", system: "musculoskeletal", name: "Tendinitis" },
    {
        id: "ms-disc",
        system: "musculoskeletal",
        name: "Slipped / Herniated Disc",
    },
    { id: "ms-stn", system: "musculoskeletal", name: "Spinal Stenosis" },

    // --- ENDOCRINE (endo) ---
    {
        id: "endo-hypo",
        system: "endocrine",
        name: "Hypothyroidism (Underactive)",
    },
    {
        id: "endo-hyper",
        system: "endocrine",
        name: "Hyperthyroidism (Overactive)",
    },
    { id: "endo-adr", system: "endocrine", name: "Adrenal Insufficiency" },
    { id: "endo-hash", system: "endocrine", name: "Hashimoto's Disease" },
    { id: "endo-pit", system: "endocrine", name: "Pituitary Disorder" },
    { id: "endo-par", system: "endocrine", name: "Hyperparathyroidism" },
    { id: "endo-cush", system: "endocrine", name: "Cushing's Syndrome" },
    { id: "endo-add", system: "endocrine", name: "Addison's Disease" },
    { id: "endo-growth", system: "endocrine", name: "Growth Hormone Issue" },
    { id: "endo-pan", system: "endocrine", name: "Pancreatic Issue" },

    // --- IMMUNE & LYMPHATIC (imm) ---
    { id: "imm-lup", system: "immune", name: "Lupus (SLE)" },
    { id: "imm-hiv", system: "immune", name: "HIV / AIDS" },
    { id: "imm-lym", system: "immune", name: "Lyme Disease" },
    { id: "imm-gra", system: "immune", name: "Graves' Disease" },
    { id: "imm-anc", system: "immune", name: "Severe Anaphylaxis History" },
    { id: "imm-sj", system: "immune", name: "Sjogren's Syndrome" },
    { id: "imm-vas", system: "immune", name: "Vasculitis" },
    { id: "imm-immu", system: "immune", name: "Immunodeficiency" },
    { id: "imm-scler", system: "immune", name: "Scleroderma" },
    { id: "imm-sar", system: "immune", name: "Sarcoidosis" },

    // --- DERMATOLOGICAL (derm) ---
    { id: "derm-ecz", system: "dermatological", name: "Eczema / Dermatitis" },
    { id: "derm-pso", system: "dermatological", name: "Psoriasis" },
    { id: "derm-ros", system: "dermatological", name: "Rosacea" },
    { id: "derm-mel", system: "dermatological", name: "Skin Cancer History" },
    { id: "derm-acn", system: "dermatological", name: "Cystic Acne" },
    { id: "derm-urt", system: "dermatological", name: "Chronic Hives" },
    { id: "derm-vit", system: "dermatological", name: "Vitiligo" },
    {
        id: "derm-inf",
        system: "dermatological",
        name: "Recurrent Skin Infections",
    },
    { id: "derm-alo", system: "dermatological", name: "Alopecia / Hair Loss" },
    {
        id: "derm-her",
        system: "dermatological",
        name: "Shingles / Herpes Zoster",
    },

    // --- URINARY (uro) ---
    { id: "uro-ckd", system: "urinary", name: "Chronic Kidney Disease" },
    { id: "uro-uti", system: "urinary", name: "Recurrent UTIs" },
    { id: "uro-stn", system: "urinary", name: "Kidney Stones" },
    { id: "uro-inc", system: "urinary", name: "Incontinence" },
    { id: "uro-cys", system: "urinary", name: "Interstitial Cystitis" },
    { id: "uro-pne", system: "urinary", name: "Pyelonephritis" },
    { id: "uro-glom", system: "urinary", name: "Glomerulonephritis" },
    { id: "uro-ovr", system: "urinary", name: "Overactive Bladder" },
    { id: "uro-dial", system: "urinary", name: "Dialysis History" },
    { id: "uro-ren", system: "urinary", name: "Renal Artery Stenosis" },

    // --- REPRODUCTIVE (repr) ---
    { id: "repr-pms", system: "reproductive", name: "Severe PMS / PMDD" },
    { id: "repr-endo", system: "reproductive", name: "Endometriosis" },
    { id: "repr-pcos", system: "reproductive", name: "PCOS" },
    {
        id: "repr-meno",
        system: "reproductive",
        name: "Menopause / Perimenopause",
    },
    { id: "repr-fib", system: "reproductive", name: "Uterine Fibroids" },
    { id: "repr-erect", system: "reproductive", name: "Erectile Dysfunction" },
    { id: "repr-bph", system: "reproductive", name: "Enlarged Prostate (BPH)" },
    { id: "repr-pros", system: "reproductive", name: "Prostate Inflammation" },
    { id: "repr-cyst", system: "reproductive", name: "Ovarian Cysts" },
    {
        id: "repr-preg",
        system: "reproductive",
        name: "Pregnancy-Related Issue",
    },

    // --- MENTAL HEALTH (ment) ---
    { id: "ment-gad", system: "mental", name: "Anxiety Disorder" },
    { id: "ment-mdd", system: "mental", name: "Clinical Depression" },
    { id: "ment-bip", system: "mental", name: "Bipolar Disorder" },
    { id: "ment-ptsd", system: "mental", name: "PTSD" },
    { id: "ment-ocd", system: "mental", name: "OCD" },
    { id: "ment-adhd", system: "mental", name: "ADHD" },
    { id: "ment-panic", system: "mental", name: "Panic Disorder" },
    { id: "ment-post", system: "mental", name: "Postpartum Depression" },
    { id: "ment-sch", system: "mental", name: "Schizophrenia" },
    { id: "ment-sad", system: "mental", name: "Seasonal Affective Disorder" },

    // --- SENSORY (sens) ---
    { id: "sens-vis", system: "sensory", name: "Vision Loss / Blurriness" },
    { id: "sens-cat", system: "sensory", name: "Cataracts" },
    { id: "sens-glau", system: "sensory", name: "Glaucoma" },
    { id: "sens-pht", system: "sensory", name: "Photosensitivity" },
    { id: "sens-hear", system: "sensory", name: "Hearing Loss" },
    { id: "sens-tin", system: "sensory", name: "Tinnitus (Ear Ringing)" },
    { id: "sens-ver", system: "sensory", name: "Vertigo / Balance" },
    { id: "sens-smel", system: "sensory", name: "Anosmia (Loss of Smell)" },
    { id: "sens-tast", system: "sensory", name: "Loss of Taste" },
    { id: "sens-touch", system: "sensory", name: "Paresthesia (Touch Loss)" },
];
